In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('data.csv')
df

,Timestamp,1_psqi,2_psqi,3_psqi,4_psqi,5a_psqi,5b_psqi,5c_psqi,5d_psqi,5e_psqi,...,4_k10,5_k10,6_k10,7_k10,8_k10,9_k10,10_k10,gpa,Unnamed: 30,Unnamed: 31
0,11/4/2021 16:05:10,1:00,15.0,9:00,7.0,Less than once a week,Less than once a week,Not during the past month,Not during the past month,Not during the past month,...,1. None of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,3.7,NaN,NaN
1,11/4/2021 16:05:23,0:30,5.0,6:30,6.5,Not during the past month,Less than once a week,Less than once a week,Not during the past month,Less than once a week,...,1. None of the time,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,1. None of the time,1. None of the time,3.1,NaN,NaN
2,11/4/2021 16:06:24,0:00,5.0,6:30,6.0,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,2. A little of the time,2. A little of the time,1. None of the time,2. A little of the time,2. A little of the time,3. Some of the time,3. Some of the time,3.3,NaN,NaN
3,11/4/2021 16:37:14,0:00,37.5,7:30,7.0,Once or twice a week,Three or more times a week,Less than once a week,Not during the past month,Not during the past month,...,5. All of the time,4. Most of the time,3. Some of the time,4. Most of the time,5. All of the time,5. All of the time,5. All of the time,2.8,NaN,NaN
4,11/4/2021 16:40:25,2:00,10.0,10:00,7.0,Less than once a week,Less than once a week,Less than once a week,Not during the past month,Not during the past month,...,3. Some of the time,3. Some of the time,1. None of the time,2. A little of the time,2. A little of the time,3. Some of the time,3. Some of the time,3.3,NaN,NaN
5,11/4/2021 16:43:22,0:30,60.0,7:00,7.0,Once or twice a week,Less than once a week,Once or twice a week,Not during the past month,Not during the past month,...,3. Some of the time,5. All of the time,5. All of the time,5. All of the time,5. All of the time,5. All of the time,5. All of the time,3.6,NaN,NaN
6,11/4/2021 17:27:07,2:30,5.0,9:30,7.5,Less than once a week,Once or twice a week,Not during the past month,Not during the past month,Not during the past month,...,4. Most of the time,1. None of the time,1. None of the time,2. A little of the time,4. Most of the time,2. A little of the time,4. Most of the time,3.1,NaN,NaN
7,11/4/2021 17:31:06,22:00,45.0,6:30,7.0,Three or more times a week,Less than once a week,Less than once a week,Not during the past month,Not during the past month,...,1. None of the time,2. A little of the time,2. A little of the time,1. None of the time,3. Some of the time,1. None of the time,1. None of the time,3.6,NaN,NaN
8,11/4/2021 19:49:59,0:00,30.0,6:30,5.5,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,4. Most of the time,1. None of the time,1. None of the time,4. Most of the time,3. Some of the time,2. A little of the time,4. Most of the time,3.4,NaN,NaN
9,11/4/2021 21:13:42,23:00,15.0,7:30,8.0,Not during the past month,Less than once a week,Not during the past month,Not during the past month,Not during the past month,...,2. A little of the time,2. A little of the time,1. None of the time,2. A little of the time,3. Some of the time,2. A little of the time,1. None of the time,3.3,NaN,NaN
10,11/4/2021 21:27:51,1:00,30.0,6:00,4.5,Three or more times a week,Once or twice a week,Not during the past month,Once or twice a week,Not during the past month,...,4. Most of the time,4. Most of the time,4. Most of the time,5. All of the time,2. A little of the time,4. Most of the time,4. Most of the time,3.3,NaN,NaN
11,11/4/2021 22:47:31,3:00,30.0,8:00,4.0,Once or twice a week,Three or more times a week,Once or twice a week,Not during the past month,Not during the past month,...,1. None of the time,2. A little of the time,3. Some of the time,3. Some of the time,3. Some of the time,2. A little of the time,2. A little of the time,3.4,NaN,NaN
12,11/5/2021 10:16:40,0:00,15.0,9:00,8.0,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,3. Some of the time,3. Some of the time,1. None of the time,3. Some of the time,3. Some of the time,3. Some of the time,3. Some of the time,3.1,NaN,NaN
13,11/5/2021 15:21:49,3:00,15.0,11:30,7.0,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,3. Some of the time,4. Most of the time,4. Most of the time,1. None of the time,4. Most of the time,1. None of the time,3. Some of the time,3.3,NaN,NaN
14,11/5/2021 16:10:59,0:00,30.0,8:30,7.0,Three or more times a week,Once or twice a week,Not during the past month,Once or twice a week,Not during the past month,...,3. Some of the time,4. Most of the time,3. Some of the time,4. Most of the time,5. All of the time,2. A little of the time,3. Some of the time,3.8,NaN,NaN
15,11/7/2021 23:39:27,0:00,30.0,8:00,7.0,Once or twice a week,Not during the past month,Once or twice a week,Not during the past month,Not during the past month,...,3. Some of the time,4. Most of the time,4. Most of the time,2. A little of the time,4. Most of the time,2. A little of the time,3. Some of the time,3.3,NaN,NaN
16,11/8/2021 2:59:02,22:30,10.0,6:30,7.5,Not during the past month,Less than once a week,Less than once a week,Less than once a week,Less than once a week,...,1. None of the time,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,1. None of the time,1. None of the time,3.1,NaN,NaN
17,11/8/2021 7:43:09,0:00,1.0,7:30,7.0,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,4. Most of the time,4. Most of the time,2. A little of the time,4. Most of the time,2. A little of the time,4. Most of the time,4. Most of the time,3.3,NaN,NaN
18,11/8/2021 9:00:35,19:30,10.0,3:30,9.5,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,3. Some of the time,1. None of the time,1. None of the time,2. A little of the time,2. A little of the time,2. A little of the time,1. None of the time,3.9,NaN,NaN
19,11/8/2021 15:39:10,2:00,5.0,9:30,6.0,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,2. A little of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,1. None of the time,3.3,NaN,NaN
20,11/8/2021 17:09:17,1:00,20.0,11:00,9.5,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,2. A little of the time,2. A little of the time,1. None of the time,2. A little of the time,4. Most of the time,2. A little of the time,2. A little of the time,3.0,NaN,NaN
21,11/15/2021 23:12:36,1:00,15.0,10:00,7.0,Once or twice a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,1. None of the time,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,1. None of the time,1. None of the time,3.7,NaN,NaN
22,11/16/2021 2:31:56,2:00,30.0,7:00,4.0,Not during the past month,Less than once a week,Not during the past month,Less than once a week,Once or twice a week,...,4. Most of the time,4. Most of the time,5. All of the time,4. Most of the time,4. Most of the time,3. Some of the time,2. A little of the time,2.3,NaN,NaN
23,11/23/2021 12:27:52,2:00,36.0,7:15,5.0,Once or twice a week,Less than once a week,Once or twice a week,Not during the past month,Once or twice a week,...,3. Some of the time,2. A little of the time,3. Some of the time,2. A little of the time,2. A little of the time,2. A little of the time,3. Some of the time,3.3,NaN,NaN
24,11/23/2021 12:36:06,23:30,20.0,7:00,6.5,Once or twice a week,Less than once a week,Not during the past month,Once or twice a week,Not during the past month,...,3. Some of the time,3. Some of the time,2. A little of the time,3. Some of the time,4. Most of the time,3. Some of the time,3. Some of the time,3.0,NaN,NaN
25,11/23/2021 16:18:36,1:00,30.0,10:00,8.0,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,1. None of the time,2. A little of the time,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,2. A little of the time,3.3,NaN,NaN
26,11/29/2021 10:21:40,1:00,10.0,8:00,6.0,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,...,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,2.8,NaN,NaN

In [3]:
df['1_psqi'].describe()

count       27
unique      11
top       0:00
freq         7
Name: 1_psqi, dtype: object

In [4]:
df['4_psqi'].mean()

6.7407407407407405

In [5]:
df_psqi = df.loc[:, '1_psqi':'9_psqi']
df_psqi

,1_psqi,2_psqi,3_psqi,4_psqi,5a_psqi,5b_psqi,5c_psqi,5d_psqi,5e_psqi,5f_psqi,5g_psqi,5h_psqi,5i_psqi,5j_psqi,6_psqi,7_psqi,8_psqi,9_psqi
0,1:00,15.0,9:00,7.0,Less than once a week,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Less than once a week,Not during the past month,NaN,Fairly bad,Not during the past month,Three or more times a week,Only a very slight problem
1,0:30,5.0,6:30,6.5,Not during the past month,Less than once a week,Less than once a week,Not during the past month,Less than once a week,Less than once a week,Not during the past month,Not during the past month,Not during the past month,NaN,Very good,Not during the past month,Less than once a week,No problem at all
2,0:00,5.0,6:30,6.0,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,NaN,Very bad,Not during the past month,Not during the past month,Only a very slight problem
3,0:00,37.5,7:30,7.0,Once or twice a week,Three or more times a week,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,NaN,Very bad,Not during the past month,Three or more times a week,Only a very slight problem
4,2:00,10.0,10:00,7.0,Less than once a week,Less than once a week,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Less than once a week,Less than once a week,Not during the past month,NaN,Very bad,Not during the past month,Once or twice a week,Only a very slight problem
5,0:30,60.0,7:00,7.0,Once or twice a week,Less than once a week,Once or twice a week,Not during the past month,Not during the past month,Less than once a week,Not during the past month,Not during the past month,Not during the past month,NaN,Very bad,Three or more times a week,Three or more times a week,A very big problem
6,2:30,5.0,9:30,7.5,Less than once a week,Once or twice a week,Not during the past month,Not during the past month,Not during the past month,Less than once a week,Not during the past month,Not during the past month,Less than once a week,NaN,Very bad,Three or more times a week,Three or more times a week,Only a very slight problem
7,22:00,45.0,6:30,7.0,Three or more times a week,Less than once a week,Less than once a week,Not during the past month,Not during the past month,Once or twice a week,Once or twice a week,Less than once a week,Not during the past month,NaN,Very bad,Not during the past month,Less than once a week,Only a very slight problem
8,0:00,30.0,6:30,5.5,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,NaN,Very good,Not during the past month,Three or more times a week,Only a very slight problem
9,23:00,15.0,7:30,8.0,Not during the past month,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Less than once a week,Less than once a week,Three or more times a week,Less than once a week,NaN,Very bad,Not during the past month,Not during the past month,Only a very slight problem
10,1:00,30.0,6:00,4.5,Three or more times a week,Once or twice a week,Not during the past month,Once or twice a week,Not during the past month,Once or twice a week,Once or twice a week,Three or more times a week,Once or twice a week,NaN,Very bad,Three or more times a week,Once or twice a week,A very big problem
11,3:00,30.0,8:00,4.0,Once or twice a week,Three or more times a week,Once or twice a week,Not during the past month,Not during the past month,Less than once a week,Not during the past month,Not during the past month,Not during the past month,NaN,Very good,Not during the past month,Not during the past month,No problem at all
12,0:00,15.0,9:00,8.0,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Less than once a week,Less than once a week,Not during the past month,Not during the past month,NaN,Very good,Once or twice a week,Once or twice a week,No problem at all
13,3:00,15.0,11:30,7.0,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Less than once a week,Less than once a week,NaN,Fairly good,Less than once a week,Less than once a week,Somewhat of a problem
14,0:00,30.0,8:30,7.0,Three or more times a week,Once or twice a week,Not during the past month,Once or twice a week,Not during the past month,Once or twice a week,Less than once a week,Three or more times a week,Once or twice a week,NaN,Fairly good,Three or more times a week,Three or more times a week,Somewhat of a problem
15,0:00,30.0,8:00,7.0,Once or twice a week,Not during the past month,Once or twice a week,Not during the past month,Not during the past month,Not during the past month,Once or twice a week,Not during the past month,Less than once a week,NaN,Very bad,Once or twice a week,Less than once a week,Somewhat of a problem
16,22:30,10.0,6:30,7.5,Not during the past month,Less than once a week,Less than once a week,Less than once a week,Less than once a week,Not during the past month,Less than once a week,Not during the past month,Not during the past month,NaN,Very bad,Not during the past month,Not during the past month,No problem at all
17,0:00,1.0,7:30,7.0,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Less than once a week,Less than once a week,NaN,Very good,Once or twice a week,Three or more times a week,No problem at all
18,19:30,10.0,3:30,9.5,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Less than once a week,Less than once a week,Once or twice a week,NaN,Very bad,Less than once a week,Less than once a week,Only a very slight problem
19,2:00,5.0,9:30,6.0,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,NaN,Very good,Not during the past month,Not during the past month,No problem at all
20,1:00,20.0,11:00,9.5,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,NaN,Fairly good,Not during the past month,Three or more times a week,Somewhat of a problem
21,1:00,15.0,10:00,7.0,Once or twice a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Once or twice a week,Not during the past month,NaN,Fairly bad,Less than once a week,Less than once a week,Only a very slight problem
22,2:00,30.0,7:00,4.0,Not during the past month,Less than once a week,Not during the past month,Less than once a week,Once or twice a week,Less than once a week,Once or twice a week,Not during the past month,Not during the past month,much work to do & the aircon was broken,Fairly good,Less than once a week,Less than once a week,Only a very slight problem
23,2:00,36.0,7:15,5.0,Once or twice a week,Less than once a week,Once or twice a week,Not during the past month,Once or twice a week,Not during the past month,Not during the past month,Less than once a week,Less than once a week,NaN,Very good,Not during the past month,Less than once a week,No problem at all
24,23:30,20.0,7:00,6.5,Once or twice a week,Less than once a week,Not during the past month,Once or twice a week,Not during the past month,Not during the past month,Not during the past month,Three or more times a week,Once or twice a week,NaN,Very bad,Less than once a week,Less than once a week,Somewhat of a problem
25,1:00,30.0,10:00,8.0,Less than once a week,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Once or twice a week,Not during the past month,Not during the past month,NaN,Very bad,Less than once a week,Once or twice a week,Only a very slight problem
26,1:00,10.0,8:00,6.0,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,Not during the past month,NaN,Very good,Three or more times a week,Three or more times a week,Only a very slight problem

In [6]:
q9 = []
for i in df_psqi['9_psqi']:
    if i == 'No problem at all':
        q9.append(0)
    elif i == 'Only a very slight problem':
        q9.append(1)
    elif i == 'Somewhat of a problem':
        q9.append(2)
    else:
        q9.append(3)
len(q9)

27

In [7]:
q2 = []
for i in df_psqi['2_psqi']:
    if i <= 15:
        q2.append(0)
    elif 16 <= i <= 30:
        q2.append(1)
    elif 31 <= i <= 60:
        q2.append(2)
    else:
        q2.append(3)
        
q5a = []
for i in df_psqi['5a_psqi']:
    if i == 'Not during the past month':
        q5a.append(0)
    elif i == 'Less than once a week':
        q5a.append(1)
    elif i == 'Once or twice a week':
        q5a.append(2)
    else:
        q5a.append(3)
        
q2_q5a = []
for i in range(len(q2)):
    if q2[i]+q5a[i] == 0:
        q2_q5a.append(0)
    elif 1 <= (q2[i]+q5a[i]) <= 2:
        q2_q5a.append(1)
    elif 3 <= (q2[i]+q5a[i]) <= 4:
        q2_q5a.append(2)
    else:
        q2_q5a.append(3)
len(q2_q5a)

27

In [8]:
q4 = []
for i in df_psqi['4_psqi']:
    if i > 7:
        q4.append(0)
    elif 6 <= i <= 7:
        q4.append(1)
    elif 5 <= i < 6:
        q4.append(2)
    else:
        q4.append(3)
len(q4)

27

In [9]:
q5b = []
for i in df_psqi['5b_psqi']:
    if i == 'Not during the past month':
        q5b.append(0)
    elif i == 'Less than once a week':
        q5b.append(1)
    elif i == 'Once or twice a week':
        q5b.append(2)
    else:
        q5b.append(3)

q5c = []
for i in df_psqi['5c_psqi']:
    if i == 'Not during the past month':
        q5c.append(0)
    elif i == 'Less than once a week':
        q5c.append(1)
    elif i == 'Once or twice a week':
        q5c.append(2)
    else:
        q5c.append(3)

q5d = []
for i in df_psqi['5d_psqi']:
    if i == 'Not during the past month':
        q5d.append(0)
    elif i == 'Less than once a week':
        q5d.append(1)
    elif i == 'Once or twice a week':
        q5d.append(2)
    else:
        q5d.append(3)

q5e = []
for i in df_psqi['5e_psqi']:
    if i == 'Not during the past month':
        q5e.append(0)
    elif i == 'Less than once a week':
        q5e.append(1)
    elif i == 'Once or twice a week':
        q5e.append(2)
    else:
        q5e.append(3)
 
q5f = []
for i in df_psqi['5f_psqi']:
    if i == 'Not during the past month':
        q5f.append(0)
    elif i == 'Less than once a week':
        q5f.append(1)
    elif i == 'Once or twice a week':
        q5f.append(2)
    else:
        q5f.append(3)
        
q5g = []
for i in df_psqi['5g_psqi']:
    if i == 'Not during the past month':
        q5g.append(0)
    elif i == 'Less than once a week':
        q5g.append(1)
    elif i == 'Once or twice a week':
        q5g.append(2)
    else:
        q5g.append(3)
        
q5h = []
for i in df_psqi['5h_psqi']:
    if i == 'Not during the past month':
        q5h.append(0)
    elif i == 'Less than once a week':
        q5h.append(1)
    elif i == 'Once or twice a week':
        q5h.append(2)
    else:
        q5h.append(3)
        
q5i = []
for i in df_psqi['5i_psqi']:
    if i == 'Not during the past month':
        q5i.append(0)
    elif i == 'Less than once a week':
        q5i.append(1)
    elif i == 'Once or twice a week':
        q5i.append(2)
    else:
        q5i.append(3)

output = []
for i in range(len(q5i)):
    output.append(q5b[i] + q5c[i] + q5d[i] + q5e[i] + q5f[i] + q5g[i] + q5h[i] + q5i[i])
    
q5b_q5j = []
for i in output:
    if i == 0:
        q5b_q5j.append(0)
    elif 1 <= i <= 9:
        q5b_q5j.append(1)
    elif 10 <= i <= 18:
        q5b_q5j.append(2)
    else:
        q5b_q5j.append(3)
len(q5b_q5j)

27

In [10]:
q6 = []
for i in df_psqi['6_psqi']:
    if i == 'Very good':
        q6.append(0)
    elif i == 'Fairly good':
        q6.append(1)
    elif i == 'Fairly bad':
        q6.append(2)
    else:
        q6.append(3)
len(q6)

27

In [11]:
q7 = []
for i in df_psqi['7_psqi']:
    if i == 'Not during the past month':
        q7.append(0)
    elif i == 'Less than once a week':
        q7.append(1)
    elif i == 'Once or twice a week':
        q7.append(2)
    else:
        q7.append(3)

q8 = []
for i in df_psqi['8_psqi']:
    if i == 'Not during the past month':
        q8.append(0)
    elif i == 'Less than once a week':
        q8.append(1)
    elif i == 'Once or twice a week':
        q8.append(2)
    else:
        q8.append(3)

q7_q8 = []
for i in range(len(q8)):
    if q7[i]+q8[i] == 0:
        q7_q8.append(0)
    elif 1 <= (q7[i]+q8[i]) <= 2:
        q7_q8.append(1)
    elif 3 <= (q7[i]+q8[i]) <= 4:
        q7_q8.append(2)
    else:
        q7_q8.append(3)
len(q7_q8)

27

In [12]:
q1_q3 = [8, 6, 6.5, 7.5, 8, 6.5, 7, 8.5, 6.5, 8.5, 5, 5, 9, 8.5, 8.5, 8, 8, 7.5, 8, 7.5, 10, 9, 5, 5, 7.5, 9, 7]

eff = []
for i in range(len(q1_q3)):
    eff.append(((df.loc[i, '4_psqi']) / (q1_q3[i])) * 100)

q1_q3_q4 = []
for i in eff:
    if i > 85:
        q1_q3_q4.append(0)
    elif 75 <= i <= 84:
        q1_q3_q4.append(1)
    elif 65 <= i <= 74:
        q1_q3_q4.append(2)
    else:
        q1_q3_q4.append(3)
len(q1_q3_q4)

27

In [13]:
df_global = pd.DataFrame(
    {'c1': q9,
     'c2': q2_q5a,
     'c3': q4,
     'c4': q1_q3_q4,
     'c5': q5b_q5j,
     'c6': q6,
     'c7': q7_q8
    })
df_global['total'] = df_global['c1'] + df_global['c2'] + df_global['c3'] + df_global['c4'] + df_global['c5'] + df_global['c6'] + df_global['c7']
df_global

    c1  c2  c3  c4  c5  c6  c7  total
0    1   1   1   0   1   2   2      8
1    0   0   1   0   1   0   1      3
2    1   0   1   0   0   3   0      5
3    1   2   1   0   1   3   2     10
4    1   1   1   0   1   3   1      8
5    3   2   1   0   1   3   3     13
6    1   1   0   0   1   3   3      9
7    1   3   1   1   1   3   1     11
8    1   1   2   3   0   0   2      9
9    1   0   0   0   1   3   0      5
10   3   2   3   0   2   3   3     16
11   0   2   3   1   1   0   0      7
12   0   1   0   0   1   0   2      4
13   2   1   1   1   1   1   1      8
14   2   2   1   1   2   1   3     12
15   2   2   1   0   1   3   2     11
16   0   0   0   0   1   3   0      4
17   0   1   1   0   1   0   3      6
18   1   0   0   0   1   3   1      6
19   0   0   1   1   0   0   0      2
20   2   1   0   0   0   1   2      6
21   1   1   1   1   1   2   1      8
22   1   1   3   1   1   1   1      9
23   0   2   2   0   1   0   1      6
24   2   2   1   0   1   3   1     10
25   1   1   0   0   1   3   2      8
26   1   0   1   0   0   0   3      5

In [14]:
df_k10 = df.loc[:, '1_k10':'10_k10']
df_k10

,1_k10,2_k10,3_k10,4_k10,5_k10,6_k10,7_k10,8_k10,9_k10,10_k10
0,5. All of the time,2. A little of the time,2. A little of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time
1,2. A little of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,1. None of the time,1. None of the time
2,3. Some of the time,1. None of the time,1. None of the time,2. A little of the time,2. A little of the time,1. None of the time,2. A little of the time,2. A little of the time,3. Some of the time,3. Some of the time
3,4. Most of the time,3. Some of the time,2. A little of the time,5. All of the time,4. Most of the time,3. Some of the time,4. Most of the time,5. All of the time,5. All of the time,5. All of the time
4,3. Some of the time,3. Some of the time,2. A little of the time,3. Some of the time,3. Some of the time,1. None of the time,2. A little of the time,2. A little of the time,3. Some of the time,3. Some of the time
5,5. All of the time,5. All of the time,4. Most of the time,3. Some of the time,5. All of the time,5. All of the time,5. All of the time,5. All of the time,5. All of the time,5. All of the time
6,4. Most of the time,3. Some of the time,2. A little of the time,4. Most of the time,1. None of the time,1. None of the time,2. A little of the time,4. Most of the time,2. A little of the time,4. Most of the time
7,2. A little of the time,3. Some of the time,2. A little of the time,1. None of the time,2. A little of the time,2. A little of the time,1. None of the time,3. Some of the time,1. None of the time,1. None of the time
8,3. Some of the time,3. Some of the time,2. A little of the time,4. Most of the time,1. None of the time,1. None of the time,4. Most of the time,3. Some of the time,2. A little of the time,4. Most of the time
9,3. Some of the time,2. A little of the time,1. None of the time,2. A little of the time,2. A little of the time,1. None of the time,2. A little of the time,3. Some of the time,2. A little of the time,1. None of the time
10,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,5. All of the time,2. A little of the time,4. Most of the time,4. Most of the time
11,1. None of the time,3. Some of the time,3. Some of the time,1. None of the time,2. A little of the time,3. Some of the time,3. Some of the time,3. Some of the time,2. A little of the time,2. A little of the time
12,3. Some of the time,3. Some of the time,3. Some of the time,3. Some of the time,3. Some of the time,1. None of the time,3. Some of the time,3. Some of the time,3. Some of the time,3. Some of the time
13,3. Some of the time,3. Some of the time,3. Some of the time,3. Some of the time,4. Most of the time,4. Most of the time,1. None of the time,4. Most of the time,1. None of the time,3. Some of the time
14,4. Most of the time,3. Some of the time,2. A little of the time,3. Some of the time,4. Most of the time,3. Some of the time,4. Most of the time,5. All of the time,2. A little of the time,3. Some of the time
15,5. All of the time,3. Some of the time,3. Some of the time,3. Some of the time,4. Most of the time,4. Most of the time,2. A little of the time,4. Most of the time,2. A little of the time,3. Some of the time
16,2. A little of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,1. None of the time,1. None of the time
17,2. A little of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,2. A little of the time,4. Most of the time,2. A little of the time,4. Most of the time,4. Most of the time
18,2. A little of the time,2. A little of the time,1. None of the time,3. Some of the time,1. None of the time,1. None of the time,2. A little of the time,2. A little of the time,2. A little of the time,1. None of the time
19,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,1. None of the time
20,4. Most of the time,3. Some of the time,1. None of the time,2. A little of the time,2. A little of the time,1. None of the time,2. A little of the time,4. Most of the time,2. A little of the time,2. A little of the time
21,2. A little of the time,3. Some of the time,2. A little of the time,1. None of the time,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,1. None of the time,1. None of the time
22,2. A little of the time,3. Some of the time,3. Some of the time,4. Most of the time,4. Most of the time,5. All of the time,4. Most of the time,4. Most of the time,3. Some of the time,2. A little of the time
23,3. Some of the time,2. A little of the time,3. Some of the time,3. Some of the time,2. A little of the time,3. Some of the time,2. A little of the time,2. A little of the time,2. A little of the time,3. Some of the time
24,3. Some of the time,3. Some of the time,3. Some of the time,3. Some of the time,3. Some of the time,2. A little of the time,3. Some of the time,4. Most of the time,3. Some of the time,3. Some of the time
25,2. A little of the time,2. A little of the time,3. Some of the time,1. None of the time,2. A little of the time,1. None of the time,1. None of the time,1. None of the time,2. A little of the time,2. A little of the time
26,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time,4. Most of the time

In [15]:
df_k10[df_k10[['1_k10', '2_k10', '3_k10', '4_k10', '5_k10', '6_k10', '7_k10', '8_k10', '9_k10', '10_k10']] == '1. None of the time'] = 1
df_k10[df_k10[['1_k10', '2_k10', '3_k10', '4_k10', '5_k10', '6_k10', '7_k10', '8_k10', '9_k10', '10_k10']] == '2. A little of the time'] = 2
df_k10[df_k10[['1_k10', '2_k10', '3_k10', '4_k10', '5_k10', '6_k10', '7_k10', '8_k10', '9_k10', '10_k10']] == '3. Some of the time'] = 3
df_k10[df_k10[['1_k10', '2_k10', '3_k10', '4_k10', '5_k10', '6_k10', '7_k10', '8_k10', '9_k10', '10_k10']] == '4. Most of the time'] = 4
df_k10[df_k10[['1_k10', '2_k10', '3_k10', '4_k10', '5_k10', '6_k10', '7_k10', '8_k10', '9_k10', '10_k10']] == '5. All of the time'] = 5
df_k10

   1_k10 2_k10 3_k10 4_k10 5_k10 6_k10 7_k10 8_k10 9_k10 10_k10
0      5     2     2     1     1     1     1     1     1      1
1      2     1     1     1     1     1     1     2     1      1
2      3     1     1     2     2     1     2     2     3      3
3      4     3     2     5     4     3     4     5     5      5
4      3     3     2     3     3     1     2     2     3      3
5      5     5     4     3     5     5     5     5     5      5
6      4     3     2     4     1     1     2     4     2      4
7      2     3     2     1     2     2     1     3     1      1
8      3     3     2     4     1     1     4     3     2      4
9      3     2     1     2     2     1     2     3     2      1
10     4     4     4     4     4     4     5     2     4      4
11     1     3     3     1     2     3     3     3     2      2
12     3     3     3     3     3     1     3     3     3      3
13     3     3     3     3     4     4     1     4     1      3
14     4     3     2     3     4     3     4     5     2      3
15     5     3     3     3     4     4     2     4     2      3
16     2     1     1     1     1     1     1     2     1      1
17     2     4     4     4     4     2     4     2     4      4
18     2     2     1     3     1     1     2     2     2      1
19     1     1     1     2     1     1     1     1     2      1
20     4     3     1     2     2     1     2     4     2      2
21     2     3     2     1     1     1     1     2     1      1
22     2     3     3     4     4     5     4     4     3      2
23     3     2     3     3     2     3     2     2     2      3
24     3     3     3     3     3     2     3     4     3      3
25     2     2     3     1     2     1     1     1     2      2
26     4     4     4     4     4     4     4     4     4      4

In [16]:
df_k10["sum"] = df_k10['1_k10'] + df_k10['2_k10'] + df_k10['3_k10'] + df_k10['4_k10'] + df_k10['5_k10'] + df_k10['6_k10'] + df_k10['7_k10'] + df_k10['8_k10'] + df_k10['9_k10'] + df_k10['10_k10']
df_k10

   1_k10 2_k10 3_k10 4_k10 5_k10 6_k10 7_k10 8_k10 9_k10 10_k10 sum
0      5     2     2     1     1     1     1     1     1      1  16
1      2     1     1     1     1     1     1     2     1      1  12
2      3     1     1     2     2     1     2     2     3      3  20
3      4     3     2     5     4     3     4     5     5      5  40
4      3     3     2     3     3     1     2     2     3      3  25
5      5     5     4     3     5     5     5     5     5      5  47
6      4     3     2     4     1     1     2     4     2      4  27
7      2     3     2     1     2     2     1     3     1      1  18
8      3     3     2     4     1     1     4     3     2      4  27
9      3     2     1     2     2     1     2     3     2      1  19
10     4     4     4     4     4     4     5     2     4      4  39
11     1     3     3     1     2     3     3     3     2      2  23
12     3     3     3     3     3     1     3     3     3      3  28
13     3     3     3     3     4     4     1     4     1      3  29
14     4     3     2     3     4     3     4     5     2      3  33
15     5     3     3     3     4     4     2     4     2      3  33
16     2     1     1     1     1     1     1     2     1      1  12
17     2     4     4     4     4     2     4     2     4      4  34
18     2     2     1     3     1     1     2     2     2      1  17
19     1     1     1     2     1     1     1     1     2      1  12
20     4     3     1     2     2     1     2     4     2      2  23
21     2     3     2     1     1     1     1     2     1      1  15
22     2     3     3     4     4     5     4     4     3      2  34
23     3     2     3     3     2     3     2     2     2      3  25
24     3     3     3     3     3     2     3     4     3      3  30
25     2     2     3     1     2     1     1     1     2      2  17
26     4     4     4     4     4     4     4     4     4      4  40

In [17]:
df_data = pd.concat([df_global['total'], df_k10['sum'], df['gpa']], axis=1, keys=['PSQI', 'K10', 'GPA'])
df_data

    PSQI K10  GPA
0      8  16  3.7
1      3  12  3.1
2      5  20  3.3
3     10  40  2.8
4      8  25  3.3
5     13  47  3.6
6      9  27  3.1
7     11  18  3.6
8      9  27  3.4
9      5  19  3.3
10    16  39  3.3
11     7  23  3.4
12     4  28  3.1
13     8  29  3.3
14    12  33  3.8
15    11  33  3.3
16     4  12  3.1
17     6  34  3.3
18     6  17  3.9
19     2  12  3.3
20     6  23  3.0
21     8  15  3.7
22     9  34  2.3
23     6  25  3.3
24    10  30  3.0
25     8  17  3.3
26     5  40  2.8

In [18]:
df_data.to_csv(r"C:\Users\Darren\OneDrive\Desktop\Darren's Career\CUHK-SZ\Courses.csv",index=False)